### ISSUE TITLE
I'm interested in participating!

### ISSUE THREAD

**Issue by bussmman** [DataChallenge-N/FS22#3]
### Name

Manuel Bussmann

### ZHAW Username

bussmman

### Free Text

The idea sounds interesting, but I am not sure yet, whether I will be available on 20 - 22 June. Is it necessary to be present all three days?

### Your status at ZHAW (optional)

Master student

### Your institute (optional)

IUNR Institut für Umwelt und Natürliche Ressourcen

**Comment by ratnanil** [comment]
Hey Manuel! Thanks for your interest! No, it's not mandatory to attend all three days, the hackdays are just an opportunity to work on the code together, synchronously. Hope you can join the challenge, we'll definitely keep you in the loop.

**Comment by ratnanil** [comment]
Dear Manuel

It would be really cool if you participate in the data challenge. I've added some slides on the nature of the data, you can see these slides here: [datachallenge-n.github.io/data](https://datachallenge-n.github.io/data)

Regrettably, this dataset is not open, and we would need you to fill out a non-disclosure agreement before we can send you the data. Can you fill out [this  NDA](https://github.com/DataChallenge-N/FS22/files/8590871/NDA.pdf) and send it back to me (you can also send it via mail to rata@zhaw.ch)?


We are looking forward to this event!

Cheers,

Nils

**Comment by ratnanil** [comment]
Thank you for sending us your NDA. I've sent you the data via mail, did you receive it? If so, your next steps are the following:

1. use our [template repo](https://github.com/DataChallenge-N/Project-template) to create a new repository on GitHub

![image](https://user-images.githubusercontent.com/12532091/166877929-ac949a4d-e0ff-406c-91bc-51beebf05531.png)

2. Add a meaningful name and description, then click on *Create repository from template*

![image](https://user-images.githubusercontent.com/12532091/166878359-e76b30a2-9bb2-4107-a7f4-8fd3bbadfb43.png)

3. Copy the URL to your Github Repo and **paste it as a reply to this post**.

![image](https://user-images.githubusercontent.com/12532091/166878921-a9dfd0dd-c0fa-4891-aa87-31e104eded00.png)

4. Open RStudio, Choose *File > New Project > Version Control > Git*. Paste the URL of your Repo 

![image](https://user-images.githubusercontent.com/12532091/166879170-02b0db56-1101-4814-8c24-c938df0830d8.png)

5. Create a new folder in your project called `data` and add the roe deer data we sent you. The content of `data` will not be uploaded to GitHub, since the folder is listed in the file `.gitignore`.

**Comment by ratnanil** [comment]
If you have **any questions**, we can schedule [a meeting](https://calendly.com/rata-zhaw/)

**Comment by bussmman** [comment]
https://github.com/bussmman/DataChallenge

**Comment by ratnanil** [comment]
I had initially sent you the data via mail. I've had to update the data slightly (added information on the sex of each roe deer), and instead of resending you the data, I've created a private repo holding the data and sent you an invitation for read access to this repo. After accepting this invitation, you will find the roe deer data here: https://github.com/DataChallenge-N/FS22_data

**Comment by ratnanil** [comment]
Hi Manuel! I haven't received a submission for the DataChallenge from you yet. Have you encountered any issues? Remember that you can always [contact me ](https://www.zhaw.ch/de/ueber-uns/person/rata/) or easily [schedule an appointment](https://calendly.com/rata-zhaw/).

**Comment by bussmman** [comment]
Hi Nils.
I'm sorry, I am not entirely sure what the submission entailes? I think, I have shared my github repository with you, where I try to keep my code updated. Or do you need something specific? The thing is, that I am still experimenting with the data, so I am not really finished with anything specific.
By the way, regarding the data challenge: I will probably only be able to join on Wednesday. However, I personally would still like to join, if that makes sense for just one day. What do you think about that?
Cheers, Manuel

**Comment by ratnanil** [comment]
> I think, I have shared my github repository with you, where I try to keep my code updated. 

Which Repo are you talking about? Looking at [your Github Profile](https://github.com/bussmman?tab=repositories), I only see 3 repos, none of which are for the DataChallenge..

**Comment by bussmman** [comment]
Oh, my bad, it was set on privat for some reason. Can you see it now?

**Comment by ratnanil** [comment]
Ok, so this is the URL to your repo: https://github.com/bussmman/DataChallenge

Cool!

**Comment by ratnanil** [comment]
Too bad that you couldn't take place, we would have loved to have you along!
