### ISSUE TITLE
I'm interested in participating!

### ISSUE THREAD

**Issue by KimboGilda** [DataChallenge-N/FS22#8]
### Name

Nikos

### ZHAW Username

bako

### Free Text

testing

### Your status at ZHAW (optional)

Employee

### Your institute (optional)

IUNR Institut für Umwelt und Natürliche Ressourcen

**Comment by ratnanil** [comment]
Dear Nikos

It would be really cool if you participate in the data challenge. I've added some slides on the nature of the data, you can see these slides here: [datachallenge-n.github.io/data](https://datachallenge-n.github.io/data)

Regrettably, this dataset is not open, and we would need you to fill out a non-disclosure agreement before we can send you the data. Can you fill out [this  NDA](https://github.com/DataChallenge-N/FS22/files/8590871/NDA.pdf) and send it back to me (you can also send it via mail to rata@zhaw.ch)?

We are looking forward to this event!

Cheers,

Nils

**Comment by ratnanil** [comment]
Thank you for sending us your NDA. I've sent you the data via mail, did you receive it? If so, your next steps are the following:

1. use our [template repo](https://github.com/DataChallenge-N/Project-template) to create a new repository on GitHub

![image](https://user-images.githubusercontent.com/12532091/166877929-ac949a4d-e0ff-406c-91bc-51beebf05531.png)

2. Add a meaningful name and description, then click on *Create repository from template*

![image](https://user-images.githubusercontent.com/12532091/166878359-e76b30a2-9bb2-4107-a7f4-8fd3bbadfb43.png)

3. Copy the URL to your Github Repo and **paste it as a reply to this post**.

![image](https://user-images.githubusercontent.com/12532091/166878921-a9dfd0dd-c0fa-4891-aa87-31e104eded00.png)

4. Open RStudio, Choose *File > New Project > Version Control > Git*. Paste the URL of your Repo 

![image](https://user-images.githubusercontent.com/12532091/166879170-02b0db56-1101-4814-8c24-c938df0830d8.png)

5. Create a new folder in your project called `data` and add the roe deer data we sent you. The content of `data` will not be uploaded to GitHub, since the folder is listed in the file `.gitignore`.

**Comment by KimboGilda** [comment]
https://github.com/KimboGilda/ChallengingWithData

**Comment by ratnanil** [comment]
I had initially sent you the data via mail. I've had to update the data slightly (added information on the sex of each roe deer), and instead of resending you the data, I've created a private repo holding the data and sent you an invitation for read access to this repo. After accepting this invitation, you will find the roe deer data here: https://github.com/DataChallenge-N/FS22_data

**Comment by ratnanil** [comment]
Hi Nikos! I haven't received a submission for the DataChallenge from you yet. Have you encountered any issues? Remember that you can always [contact me ](https://www.zhaw.ch/de/ueber-uns/person/rata/) or easily [schedule an appointment](https://calendly.com/rata-zhaw/).
